apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: localhost:5000/config-service:1.2.0
          ports:
            - containerPort: 9999
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "localhost:5000/discovery-service:8761/eureka"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8761
              path: /discovery-service/actuator/health
