apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          # L'image utilise le registre local et le numéro de build défini dans Jenkins
          image: localhost:5000/account-service:${BUILD_NUMBER}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          env:
            - name: CONFIG_SERVICE_URL
              value: "http://config-service:9999"
            - name: DISCOVERY_SERVICE_URL
              value: "http://discovery-service:8761/eureka"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: ClusterIP
  ports:
    - port: 8082  # Port du service exposé sur le cluster Kubernetes
      targetPort: 8082 # Port sur lequel votre service d'authentification écoute dans le pod
      protocol: TCP
      name: http
  selector:
    app: account-service